version: "3.8"

services:
  db:
    image: postgres:17
    container_name: ${DB_NAME}_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
      args:
        - PORT=${BACKEND_PORT}
    container_name: ${PROJECT_NAME}_backend
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public
      - PORT=${BACKEND_PORT}
    expose:
      - ${BACKEND_PORT}
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}_nginx
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
